#!/usr/bin/env python3
"""Write one page per language from a template and its string file.

    python3 tools/build.py

Templates live in templates/ and carry the English text plus a data-i18n key on
every element that holds words. Strings live in i18n/<page>.<lang>.json. English
lands at the site root, every other language under its own folder, so each
language is a real page with a real address.

Edit a template or a string file, then run this. Never edit the generated pages.
"""

import hashlib
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://solidshare.app"

LANGS = [
    ("en", "English"),
    ("de", "Deutsch"),
    ("es", "Español"),
    ("fr", "Français"),
    ("it", "Italiano"),
]

# page key -> (template, output path per language)
PAGES = {
    "home": ("templates/index.html", lambda lang: "index.html" if lang == "en" else "%s/index.html" % lang),
    "privacy": ("templates/privacy.html", lambda lang: "privacy/index.html" if lang == "en" else "%s/privacy/index.html" % lang),
}

# page key -> address of that page, per language
ADDRESS = {
    "home": lambda lang: "/" if lang == "en" else "/%s/" % lang,
    "privacy": lambda lang: "/privacy" if lang == "en" else "/%s/privacy" % lang,
}

BANNER = (
    "<!-- Generated by tools/build.py from %s and i18n/%s.%s.json.\n"
    "     Edit those, then run the script again. Changes made here are lost. -->\n"
)

TAG = re.compile(r"<(/?)([a-zA-Z0-9-]+)((?:\s[^>]*?)?)(/?)>", re.S)
VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}


def read(path):
    return io.open(os.path.join(ROOT, path), encoding="utf-8").read()


def write(path, text):
    full = os.path.join(ROOT, path)
    folder = os.path.dirname(full)
    if folder and not os.path.isdir(folder):
        os.makedirs(folder)
    io.open(full, "w", encoding="utf-8").write(text)


def put_text(html, strings, missing):
    """Replace the contents of every element that carries a data-i18n key."""
    out = []
    pos = 0
    toks = list(TAG.finditer(html))
    index = {m.start(): i for i, m in enumerate(toks)}
    i = 0
    while i < len(toks):
        m = toks[i]
        key = re.search(r'\sdata-i18n="([^"]+)"', m.group(3) or "")
        if m.group(1) or not key:
            i += 1
            continue
        # Find this element's closing tag.
        depth, j = 1, i + 1
        while j < len(toks) and depth:
            closing, tag2 = toks[j].group(1), toks[j].group(2).lower()
            if not closing and tag2 not in VOID and not toks[j].group(4):
                depth += 1
            elif closing:
                depth -= 1
            j += 1
        if depth:
            sys.exit("unclosed element for key %s" % key.group(1))
        close = toks[j - 1]
        value = strings.get(key.group(1))
        if value is None:
            missing.add(key.group(1))
            i += 1
            continue
        out.append(html[pos:m.end()])
        out.append(value)
        pos = close.start()
        # Carry on after the element we just filled.
        i = index[close.start()] + 1
    out.append(html[pos:])
    return "".join(out)


def put_attributes(html, strings, missing):
    """data-i18n-alt / -label / -content name the attribute they translate."""
    pairs = [("data-i18n-alt", "alt"), ("data-i18n-label", "aria-label"), ("data-i18n-content", "content")]

    def one(match):
        raw = match.group(0)
        for marker, attr in pairs:
            found = re.search(r'\s%s="([^"]+)"' % marker, raw)
            if not found:
                continue
            value = strings.get(found.group(1))
            if value is None:
                missing.add(found.group(1))
                continue
            if '"' in value or "<" in value:
                sys.exit("%s cannot hold markup or a quote: %r" % (found.group(1), value))
            raw = re.sub(r'\s%s="[^"]*"' % attr, "", raw, count=1)
            raw = raw.replace(found.group(0), ' %s="%s"' % (attr, value))
        return raw

    return TAG.sub(one, html)


def stamp(html):
    """Point at /style.css?v=<fingerprint>, so an update is never held back by a cache.

    Cloudflare serves these files with a four-hour cache. Without the fingerprint a
    reader who visited this morning gets today's markup wearing yesterday's styles.
    """
    for path, attr in (("/style.css", "href"), ("/main.js", "src")):
        target = os.path.join(ROOT, path.lstrip("/"))
        if not os.path.exists(target):
            continue
        digest = hashlib.sha256(io.open(target, "rb").read()).hexdigest()[:8]
        html = html.replace('%s="%s"' % (attr, path), '%s="%s?v=%s"' % (attr, path, digest))
    return html


def picker(page, lang, label):
    """A plain list of links: the same page, in the other languages."""
    rows = []
    for code, name in LANGS:
        here = ' aria-current="true"' if code == lang else ""
        rows.append(
            '    <li><a href="%s" hreflang="%s" lang="%s"%s>%s</a></li>'
            % (ADDRESS[page](code), code, code, here, name)
        )
    current = dict(LANGS)[lang]
    return (
        '<details class="lang">\n'
        '  <summary aria-label="%s">\n'
        '    <svg viewBox="0 0 24 24" aria-hidden="true">\n'
        '      <circle cx="12" cy="12" r="9" />\n'
        '      <path d="M3 12h18" />\n'
        '      <path d="M12 3a14 14 0 0 1 0 18a14 14 0 0 1 0-18Z" />\n'
        '    </svg>\n'
        '    <span>%s</span>\n'
        '  </summary>\n'
        '  <ul>\n%s\n  </ul>\n'
        '</details>' % (label, current, "\n".join(rows))
    )


def head_links(page, lang):
    """One canonical address for this page, and a pointer to each translation."""
    rows = ['    <link rel="canonical" href="%s%s" />' % (SITE, ADDRESS[page](lang))]
    for code, _ in LANGS:
        rows.append('    <link rel="alternate" hreflang="%s" href="%s%s" />' % (code, SITE, ADDRESS[page](code)))
    rows.append('    <link rel="alternate" hreflang="x-default" href="%s%s" />' % (SITE, ADDRESS[page]("en")))
    return "\n".join(rows)


def faq_schema(strings, lang):
    """The FAQ answers the page itself shows, in the language it shows them in."""
    plain = lambda s: re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", s)).strip()
    entries = []
    number = 3
    while ("faq.%d" % (number + 1)) in strings:
        entries.append({
            "@type": "Question",
            "name": plain(strings["faq.%d" % number]),
            "acceptedAnswer": {"@type": "Answer", "text": plain(strings["faq.%d" % (number + 1)])},
        })
        number += 2
    return json.dumps(
        {"@context": "https://schema.org", "@type": "FAQPage", "inLanguage": lang, "mainEntity": entries},
        ensure_ascii=False, indent=2,
    )


def build_page(page, lang):
    template_path, output_for = PAGES[page]
    template = read(template_path)
    strings = json.loads(read("i18n/%s.%s.json" % (page, lang)))
    missing = set()

    html = put_text(template, strings, missing)
    html = put_attributes(html, strings, missing)
    if missing:
        sys.exit("%s/%s has no string for: %s" % (page, lang, ", ".join(sorted(missing))))

    html = html.replace('<html lang="en">', '<html lang="%s">' % lang, 1)

    # One canonical address and the translation pointers, in place of the old canonical.
    html = re.sub(r'    <link rel="canonical"[^>]*/>', head_links(page, lang), html, count=1)
    html = re.sub(r'(<meta property="og:url" content=")[^"]*(")', r"\1%s%s\2" % (SITE, ADDRESS[page](lang)), html, count=1)

    # Links between the pages of this site follow the reader's language. This runs
    # before the picker goes in, because the picker's links are already addressed.
    html = html.replace('href="/"', 'href="%s"' % ADDRESS["home"](lang))
    html = html.replace('href="/privacy"', 'href="%s"' % ADDRESS["privacy"](lang))

    block = picker(page, lang, strings.get("nav.lang", "Language"))
    spot = re.search(r"([ \t]*)<div data-lang-picker></div>", html)
    if spot:
        indent = spot.group(1)
        block = "\n".join(indent + line if i else line for i, line in enumerate(block.split("\n")))
        html = html[:spot.start()] + indent + block + html[spot.end():]

    if page == "home":
        html = html.replace('"url": "https://solidshare.app/"', '"url": "%s%s"' % (SITE, ADDRESS[page](lang)))
        html = re.sub(
            r'(<script type="application/ld\+json">\s*)\{\s*"@context": "https://schema\.org",\s*"@type": "FAQPage".*?\}(\s*</script>)',
            lambda m: m.group(1) + faq_schema(strings, lang) + m.group(2),
            html, count=1, flags=re.S,
        )
        html = html.replace(
            '"description": "Solid Share turns your Solid pod into a personal data wallet on Android. Browse files, keep contacts, tickets and passes, and share them by WebID, link or QR code."',
            '"description": %s' % json.dumps(strings["meta.description"], ensure_ascii=False),
        )

    html = stamp(html)

    # The keys did their work; the published page does not need them.
    html = re.sub(r' data-i18n(?:-alt|-label|-content)?="[^"]*"', "", html)

    out = output_for(lang)
    write(out, BANNER % (template_path, page, lang) + html)
    return out


def sitemap():
    rows = ['<?xml version="1.0" encoding="UTF-8"?>',
            '<urlset xmlns="http://www.w3.org/1999/xhtml/sitemap" '
            'xmlns:x="http://www.w3.org/1999/xhtml">'.replace(
                "http://www.w3.org/1999/xhtml/sitemap", "http://www.sitemaps.org/schemas/sitemap/0.9")]
    for page in ("home", "privacy"):
        for lang, _ in LANGS:
            rows.append("  <url>")
            rows.append("    <loc>%s%s</loc>" % (SITE, ADDRESS[page](lang)))
            for other, _n in LANGS:
                rows.append('    <x:link rel="alternate" hreflang="%s" href="%s%s"/>' % (other, SITE, ADDRESS[page](other)))
            rows.append("  </url>")
    rows.append("</urlset>")
    write("sitemap.xml", "\n".join(rows) + "\n")
    return "sitemap.xml"


if __name__ == "__main__":
    written = []
    for page in PAGES:
        for lang, _ in LANGS:
            written.append(build_page(page, lang))
    written.append(sitemap())
    for path in written:
        print("wrote", path)
